function isX_SRMT = count4Type_PC(data, i_mouse, i_mouseDay, j_mouseDay, typeIdx)

%% typeIdx 1:space, 2:reward, 3:mix, 4:type-free

if typeIdx == 1
    isX_SRMT = data{i_mouse, i_mouseDay}.isSpaceSpaceIdx{j_mouseDay} + ...
        2 * data{i_mouse, i_mouseDay}.isSpaceRewardIdx{j_mouseDay} + ...
        3 * data{i_mouse, i_mouseDay}.isSpaceMixIdx{j_mouseDay} + ...
        4 * data{i_mouse, i_mouseDay}.isSpaceTypeFreeIdx{j_mouseDay};
elseif typeIdx == 2
    isX_SRMT = data{i_mouse, i_mouseDay}.isRewardSpaceIdx{j_mouseDay} + ...
        2 * data{i_mouse, i_mouseDay}.isRewardRewardIdx{j_mouseDay} + ...
        3 * data{i_mouse, i_mouseDay}.isRewardMixIdx{j_mouseDay} + ...
        4 * data{i_mouse, i_mouseDay}.isRewardTypeFreeIdx{j_mouseDay};
elseif typeIdx == 3
    isX_SRMT = data{i_mouse, i_mouseDay}.isMixSpaceIdx{j_mouseDay} + ...
        2 * data{i_mouse, i_mouseDay}.isMixRewardIdx{j_mouseDay} + ...
        3 * data{i_mouse, i_mouseDay}.isMixMixIdx{j_mouseDay} + ...
        4 * data{i_mouse, i_mouseDay}.isMixTypeFreeIdx{j_mouseDay};
    % isTypeFree version not implemented at first
% % % elseif typeIdx == 4
% % %     isX_SRMT = data{i_mouse, i_mouseDay}.isTypeFreeSpaceIdx{j_mouseDay} + ...
% % %         2 * data{i_mouse, i_mouseDay}.isTypeFreeRewardIdx{j_mouseDay} + ...
% % %         3 * data{i_mouse, i_mouseDay}.isTypeFreeMixIdx{j_mouseDay} + ...
% % %         4 * data{i_mouse, i_mouseDay}.isTypeFreeTypeFreeIdx{j_mouseDay};
% % %     
    
end